files:
  input:
    reference: ~/reference/ucsc_hg19.fa
  output:
    outputdirectory : ~/mysim
    sequencing: paired-end
    readlength: 101
    averageinsertsize: 400
    sd: 50
    baseerrorrate: 0.2
    coverage: 30

variants:
  DEL:
    range:
      - 10-20
      - 20-30
    number:
      - 20
      - 30