file:
  input:
    reference: ~/reference/ucsc_hg19.fa
  output:
    outputdirectory : ~/mysim
    sequencing: paired-end
    readlength: 101
    averageinsertsize: 400
    sd: 50
    baseerrorrate: 0.2
    coverage: 30

variant:
  - type: DEL
    spec:
      - range: 50-100
        number: 50
      - range: 101-1000
        number: 100
      - range: 2000-10000
        number: 500
  - type: INS
    spec:
      - range: 10-1000
        number: 50
      - range: 1001-10000
        number: 10
      - range: 10001-20000
        number: 5