name: MacOS
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install miniconda
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install gcc
          export CC=/usr/local/bin/gcc-9
          export CXX=/usr/local/bin/g++-9
          if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
              wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
          else
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
          fi
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          conda config --set always_yes yes
          conda update -q conda
          conda install -y -c bioconda seqan3
          conda install -y -c anaconda cmake
          mkdir build && cd build && cmake .. -DINCLUDE_LIBRARY_PREFIX=$HOME/miniconda/include -DLIBRARY_LINK_PREFIX=$HOME/miniconda/lib/ -DBUILD_TESTS=ON
      - name: Build
        run: cd build && make
      - name: Testing
        run: cd build && ctest --verbose
      - name: Install
        run: cd build && sudo make install
      - name: Run forge
        run: forge
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: forge_linux_x86_64bit
          path: /usr/local/bin/forge